api: https://10.10.1.202:9200
username: elastic
password: elastic
index: .ds-traces-apm-default-2023.04.05-000001
pods:
  - adservice
  - cartservice
  - checkoutservice
  - currencyservice
  - emailservice
  - frontend
  - paymentservice
  - productcatalogservice
  - recommendationservice
  - redis
  - shippingservice

